version: "3.9"

services:
  postgres:
    image: postgres:14.3-alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: app
    ports:
      - 5432:5432
    networks:
      - courses_backend-network
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  courses_backend-network:
    driver: bridge